branches:
  only:
    - docsNZ

install:
  - cmd: pip install mkdocs

build_script:
  - cmd: mkdocs build --config-file mkdocs.yml

artifacts:
  - path: posdocsAU
    name: posdocsAU
    type: zip

deploy:
  - provider: S3
    access_key_id: UvGZuMN7cMD8Sa0hN5v2tky70NJZsxDiKWQaau/+s8E=
    secret_access_key:
      secure: mMKmFPTJVUqgGIgJ+dJW0lCMYxJx4x8Vuv7KriN/AVh6vnv7gy3wn1ixsOOKT3nq
    bucket: posdocs2.oxipay.com.au
    region: ap-southeast-2
    unzip: true
    set_public: true
    artifact: posdocsAU

notifications:
  - provider: Email
    to:
      - michael.hermann@certegy.com.au
  - provider: Slack
    auth_token:
      secure: yXpzER0fyDmh7wYR6zrrES+wGzz5010OpUvpb5UPMsQZO12Ag3TaeOjSsZ0tDQQ4WaNoNngsPOPiaYWmsfg3fhJrSyPy240FqSwDdhSPqC0=
    channel: '#alerts'
