site_name: Oxipay POS Integration
pages:
- Home: 'index.md'
- Resources:  
   - Introduction: 'resources/introduction.md'
   - Processes: 
        - Device Initialisation / Setup: 'resources/processes/device_setup.md'        
        - Customer Initiated: 'resources/processes/customer_initiated.md'
        - Merchant Initiated: 'resources/processes/merchant_initiated.md'
        - Invite: 'resources/processes/invite.md'        
        - Receipt: 'resources/processes/receipt.md'
        - SalesAdjustment: 'resources/processes/adjustment.md'
   - API Reference: 'resources/api_reference.md'
theme: readthedocs
extra_css: [css/jquery.modal.min.css, css/custom.css]
